### ISSUE TITLE
総務省Web-API利用規約第３条について

### ISSUE THREAD

**Issue by jr8ppg** [jucky154/soumuAPI#1]
Web-API利用規約第３条に基づいての表示がいると思いますよ。
https://www.tele.soumu.go.jp/j/musen/webapi/kiyaku/index.htm

**Comment by jucky154** [comment]
ご指摘ありがとうございます。
ReadMeに追加しておきます。
また、検索画面にメニューを作り表示できるように対応します。

**Comment by JG1VPP** [comment]
メニューを作るのであれば、WinAPIでzLog本体に追加する手があります。

```go
package main

import (
	"fmt"
	"unsafe"
	"github.com/gonutz/w32"
)

func init() {
	OnLaunchEvent = onLaunchEvent
	OnWindowEvent = onWindowEvent
}

func onLaunchEvent() {
	hMenu1 := w32.HMENU(GetUI("MainForm.MainMenu"))
	hMenu2 := w32.CreateMenu()
	w32.AppendMenu(hMenu1, w32.MF_POPUP, hMenu2, "総務省API")
	w32.AppendMenu(hMenu2, w32.MF_STRING, 10001, "ウィンドウを開く")
	w32.AppendMenu(hMenu2, w32.MF_STRING, 10002, "利用規約")
	w32.DrawMenuBar(w32.HWND(GetUI("MainForm")))
}

func onWindowEvent(ptr uintptr) {
	msg := (*w32.MSG)(unsafe.Pointer(ptr))
	if msg.Message = w32.WM_COMMAND {
		switch msg.WParam {
 		case 10001:
			// ウィンドウを開く
		case 10002:
			// 利用規約を開く
		}
	}
}
```

**Comment by jucky154** [comment]
https://github.com/jucky154/soumuAPI/commit/b590a698730c1ab32b55931164379cb0f073fb3c
において対応しました。
![menu](https://user-images.githubusercontent.com/58735989/181285627-33d2cf86-d610-427f-8517-179a97354d22.png)
メニューに利用規約とウィンドウを開くを用意しました。そして、第３条を満たすような表示を追加しました。
![kiyaku](https://user-images.githubusercontent.com/58735989/181285845-1b45e08e-9d6f-4b04-94b5-49f50d9834ce.png)
![checklist](https://user-images.githubusercontent.com/58735989/181285857-8082eb6c-f4c8-4b5f-a0e3-27663be52055.png)

また、周波数についてはzLog本体から取得するのでコンボボックスを廃止しました。
ウィンドウもメニューから開けるようになったので、バッテンを押したさいに適切にウィンドウが消えるようにしました。
