### ISSUE TITLE
zLog 2.8.6.6で使用するとzLogが落ちる

### ISSUE THREAD

**Issue by jkitagawa** [jucky154/soumuAPI#6]
zLog 2.8.6.6 令和で使用するとzLog本体が落ちるようです．以前は正常に動いていました．

**Comment by jucky154** [comment]
issueありがとうございます
後ほど、詳しい調査を行いますが、現在考えられる原因としては、zLog 2.8.6.6 令和との相性ではなく、総務省側のAPIが変化したことが原因だと思われます。

総務省のAPIから周波数情報が消えたので、そちらに対応しようと考えていたところ
https://twitter.com/JR3BWF/status/1708958562872115297
のようにすれば、周波数情報が読めるらしいという情報や、その内容が間違ったものも含まれているという情報も錯綜しており、対応に苦慮しているところでした。

ACAGも今週末なので、周波数情報なしで修正を検討いたします。

**Comment by jkitagawa** [comment]
なるほど，そういうことでしたか．確かに総務省側の表記が変わったことが影響しているのかもしれませんね．

**Comment by jucky154** [comment]
![ã¹ã¯ãªã¼ã³ã·ã§ãã 2023-10-05 224557](https://github.com/jucky154/soumuAPI/assets/58735989/ec820a9e-1e5c-46b4-a7dd-8215fd2f008f)

上のように修正をしました。
これまでAPIから入力中の周波数が使えるかを確認していましたが、新しい形式では対応できないので、免許の種類のみ掲載します。

総務省APIのプラグインをプラグインマネージャーより新しくインストールしてご確認いただけると幸いです。

**Comment by jkitagawa** [comment]
動作確認しました．早速のご対応ありがとうございました．
JS6RTJ
