### ISSUE TITLE
md5ファイルがよろしくない

### ISSUE THREAD

**Issue by jr8ppg** [jucky154/soumuAPI#7]
md5ファイルが古いようで、verifyすると常に不一致になります。
https://github.com/jucky154/soumuAPI/releases/download/nightly/soumuAPI.dll.md5

PluginManagerには別の不具合もあって、プラグインの新規インストール時はmd5の検査が行われません。
disable→installと行うとmd5の検査を行いますが、常に不一致となります。

**Comment by jucky154** [comment]
この問題ですが、@JG1VPP
https://github.com/jucky154/soumuAPI/releases/tag/nightly
を見ると、md5とDLLの日付が一致するものと、一致しない余計なmd5が存在するように見えることが問題ということでいいでしょうか？　

Plugin Mangerの件はZyLo側のissueに転載します

**Comment by jr8ppg** [comment]
soumuAPI.md5 のファイル名が間違っているといえばいいのかな。

正しくは　soumuAPI.dll.md5 というファイル名で作成されなければいけないのに、soumuAPI.md5で作成されている。
PluginManagerは更新されていないsoumuAPI.dll.md5をダウンロードするので常に不一致となります。

こちらと同じ話と思います。
https://github.com/nextzlog/todo/issues/153#issuecomment-2098232327

**Comment by jucky154** [comment]
https://github.com/jucky154/manage_zylo/blob/b771824fdd167ec8e154cade9a38f455225e83c7/market.toml#L38
で正しいものsoumuAPI.dll.md5　を連れてくる設定にも関わらず、
https://github.com/jucky154/soumuAPI/commit/4144136a2be0a1de5d80d74a856b026f3fdf39bc
のように古いZyLOを使う設定でActionが行われる設定になっていたため、ハッシュがおかしくなっていました

そのため、version指定を削除することで、対応しました
おそらく、これで解決すると思います

**Comment by jr8ppg** [comment]
確認しました。OKになりました。ありがとうございます。
